<script lang="ts">
	import { generationState } from '$lib/state/generation.svelte';
	import { pdfGenerator, type PDFOptions } from '$lib/pdf/generator';
	import { svgStringToPdfBlob } from '$lib/pdf/svg-to-pdf';
	import { getActivityMeta } from '$lib/activities/registry';
	import Button from '$lib/components/ui/Button.svelte';

	let includeAnswerKey = $state(true);
	let grayscale = $state(false);
	let showBorder = $state(true);
	let isDownloading = $state(false);
	let downloadError = $state<string | null>(null);

	/**
	 * Build the worksheet SVG string from the current generation state.
	 */
	function buildWorksheetSvg(): string {
		const A4_W = 210;
		const A4_H = 297;
		const MARGIN = 15;
		const HEADER_H = 25;
		const INSTR_GAP = 4;

		const activities = generationState.streamedActivities;
		const subject = generationState.config.subject ?? 'Worksheet';
		const age = generationState.config.age ?? '';

		const contentX = MARGIN;
		const contentW = A4_W - 2 * MARGIN;
		const contentTop = MARGIN + HEADER_H + INSTR_GAP;
		const contentBottom = A4_H - MARGIN;
		const totalH = contentBottom - contentTop;
		const gapBetween = 3;
		const perActivity = activities.length > 0
			? (totalH - gapBetween * (activities.length - 1)) / activities.length
			: totalH;

		// Build activity blocks as simple SVG
		const activityBlocks = activities.map((activity, i) => {
			const y = contentTop + i * (Math.max(perActivity, 20) + gapBetween);
			const h = Math.max(perActivity, 20);
			const meta = getActivityMeta(activity.type);
			const label = meta?.name ?? activity.type;

			return `
				<g transform="translate(${contentX}, ${y})">
					<text x="0" y="5" font-size="3.5" font-weight="700" fill="#374151">Q${i + 1}. ${escapeXml(activity.title)}</text>
					<text x="0" y="10" font-size="2.5" fill="#6b7280">${escapeXml(activity.instructions)}</text>
					<rect x="0" y="13" width="${contentW}" height="${h - 15}" fill="none" stroke="#e5e7eb" stroke-width="0.2" stroke-dasharray="2,1" rx="1" />
					<text x="${contentW / 2}" y="${13 + (h - 15) / 2}" text-anchor="middle" dominant-baseline="middle" font-size="2.5" fill="#d1d5db">[${escapeXml(label)}]</text>
				</g>
			`;
		}).join('\n');

		const borderSvg = showBorder
			? `<rect x="5" y="5" width="${A4_W - 10}" height="${A4_H - 10}" fill="none" stroke="#e5e7eb" stroke-width="0.3" rx="2" />`
			: '';

		const filterAttr = grayscale ? ' filter="url(#grayscale)"' : '';
		const grayscaleFilter = grayscale
			? `<defs><filter id="grayscale"><feColorMatrix type="saturate" values="0"/></filter></defs>`
			: '';

		return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${A4_W} ${A4_H}" width="210mm" height="297mm" style="font-family: Comic Neue, sans-serif"${filterAttr}>
${grayscaleFilter}
<rect width="${A4_W}" height="${A4_H}" fill="white" />
${borderSvg}
<g transform="translate(${MARGIN}, ${MARGIN})">
	<text x="${contentW / 2}" y="8" text-anchor="middle" font-size="7" font-weight="700" fill="#1f2937">${escapeXml(subject)}</text>
	<text x="${contentW / 2}" y="14" text-anchor="middle" font-size="3" fill="#9ca3af">Age ${age} - ${activities.length} Activities</text>
	<text x="0" y="22" font-size="2.5" fill="#9ca3af">Name: ________________________</text>
	<text x="${contentW}" y="22" text-anchor="end" font-size="2.5" fill="#9ca3af">Date: ____________</text>
	<line x1="0" y1="${HEADER_H}" x2="${contentW}" y2="${HEADER_H}" stroke="#e5e7eb" stroke-width="0.3" />
</g>
${activityBlocks}
<text x="${A4_W / 2}" y="${A4_H - 8}" text-anchor="middle" font-size="2" fill="#d1d5db">Generated by WorksheetWiz</text>
</svg>`;
	}

	function escapeXml(str: string): string {
		return str
			.replace(/&/g, '&amp;')
			.replace(/</g, '&lt;')
			.replace(/>/g, '&gt;')
			.replace(/"/g, '&quot;')
			.replace(/'/g, '&apos;');
	}

	async function handleDownloadPDF() {
		isDownloading = true;
		downloadError = null;

		try {
			const svgString = buildWorksheetSvg();
			const blob = await svgStringToPdfBlob(svgString);
			const subject = generationState.config.subject ?? 'worksheet';
			const age = generationState.config.age ?? '';
			const filename = `${subject}-age${age}-worksheet.pdf`;
			pdfGenerator.downloadPDF(blob, filename);
		} catch (err) {
			console.error('PDF generation failed:', err);
			downloadError = err instanceof Error ? err.message : 'PDF generation failed';
		} finally {
			isDownloading = false;
		}
	}

	function handlePrint() {
		window.print();
	}

	function handleSaveTemplate() {
		try {
			const data = {
				config: generationState.config,
				activities: generationState.streamedActivities,
				savedAt: new Date().toISOString()
			};
			const key = `worksheet-template-${Date.now()}`;
			localStorage.setItem(key, JSON.stringify(data));

			// Also save to a list of templates
			const templateList = JSON.parse(localStorage.getItem('worksheet-templates') ?? '[]');
			templateList.push({
				key,
				subject: generationState.config.subject,
				age: generationState.config.age,
				activityCount: generationState.streamedActivities.length,
				savedAt: data.savedAt
			});
			localStorage.setItem('worksheet-templates', JSON.stringify(templateList));
			alert('Template saved successfully!');
		} catch {
			alert('Failed to save template. Storage may be full.');
		}
	}

	function handleCreateAnother() {
		generationState.reset();
	}
</script>

<div class="space-y-8">
	<div>
		<h2 class="text-2xl font-bold text-gray-900 font-display">Download Your Worksheet</h2>
		<p class="text-gray-500 mt-1">Choose your format and download options</p>
	</div>

	<div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
		<!-- Left: Preview thumbnail -->
		<div>
			<div class="bg-gray-100 rounded-xl p-6 flex justify-center">
				<div class="w-[210px] h-[297px] bg-white rounded shadow-md overflow-hidden" style="font-size: 4px;">
					<div class="p-3">
						<!-- Mini header -->
						<div class="text-center border-b border-gray-200 pb-1 mb-2">
							<p class="font-bold text-gray-700 capitalize" style="font-size: 6px;">
								{generationState.config.subject ?? 'Worksheet'}
							</p>
							<p class="text-gray-400" style="font-size: 3px;">
								Age {generationState.config.age ?? ''} &middot; {generationState.streamedActivities.length} Activities
							</p>
						</div>

						<!-- Mini activity previews -->
						{#each generationState.streamedActivities.slice(0, 6) as activity, i}
							<div class="mb-1.5">
								<div class="flex items-baseline gap-0.5">
									<span class="font-bold text-gray-600" style="font-size: 3.5px;">Q{i + 1}.</span>
									<span class="font-medium text-gray-700 truncate" style="font-size: 3.5px;">{activity.title}</span>
								</div>
								<div class="mt-0.5 mx-2 h-3 border border-dashed border-gray-200 rounded-sm"></div>
							</div>
						{/each}
						{#if generationState.streamedActivities.length > 6}
							<p class="text-center text-gray-400" style="font-size: 3px;">
								+{generationState.streamedActivities.length - 6} more activities
							</p>
						{/if}
					</div>
				</div>
			</div>

			<!-- Activity count summary -->
			<div class="mt-4 flex items-center justify-center gap-4 text-sm text-gray-500">
				<div class="flex items-center gap-1.5">
					<svg class="w-4 h-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
						<path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
					</svg>
					<span>1 page</span>
				</div>
				<div class="flex items-center gap-1.5">
					<svg class="w-4 h-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
						<path stroke-linecap="round" stroke-linejoin="round" d="M3.75 12h16.5m-16.5 3.75h16.5M3.75 19.5h16.5M5.625 4.5h12.75a1.875 1.875 0 010 3.75H5.625a1.875 1.875 0 010-3.75z" />
					</svg>
					<span>{generationState.streamedActivities.length} activities</span>
				</div>
			</div>
		</div>

		<!-- Right: Download options -->
		<div class="space-y-6">
			<!-- Options checkboxes -->
			<div class="bg-white rounded-xl border border-gray-200 p-5 space-y-4">
				<h3 class="text-sm font-semibold text-gray-800">Options</h3>

				<label class="flex items-center gap-3 cursor-pointer group">
					<div class="relative">
						<input
							type="checkbox"
							bind:checked={includeAnswerKey}
							class="peer sr-only"
						/>
						<div class="w-5 h-5 rounded-md border-2 border-gray-300 peer-checked:border-primary peer-checked:bg-primary transition-all flex items-center justify-center">
							{#if includeAnswerKey}
								<svg class="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3">
									<path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
								</svg>
							{/if}
						</div>
					</div>
					<div>
						<span class="text-sm font-medium text-gray-700 group-hover:text-gray-900">Include Answer Key</span>
						<p class="text-xs text-gray-400">Adds an answer page at the end</p>
					</div>
				</label>

				<label class="flex items-center gap-3 cursor-pointer group">
					<div class="relative">
						<input
							type="checkbox"
							bind:checked={grayscale}
							class="peer sr-only"
						/>
						<div class="w-5 h-5 rounded-md border-2 border-gray-300 peer-checked:border-primary peer-checked:bg-primary transition-all flex items-center justify-center">
							{#if grayscale}
								<svg class="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3">
									<path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
								</svg>
							{/if}
						</div>
					</div>
					<div>
						<span class="text-sm font-medium text-gray-700 group-hover:text-gray-900">Grayscale</span>
						<p class="text-xs text-gray-400">Black and white for easier printing</p>
					</div>
				</label>

				<label class="flex items-center gap-3 cursor-pointer group">
					<div class="relative">
						<input
							type="checkbox"
							bind:checked={showBorder}
							class="peer sr-only"
						/>
						<div class="w-5 h-5 rounded-md border-2 border-gray-300 peer-checked:border-primary peer-checked:bg-primary transition-all flex items-center justify-center">
							{#if showBorder}
								<svg class="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3">
									<path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
								</svg>
							{/if}
						</div>
					</div>
					<div>
						<span class="text-sm font-medium text-gray-700 group-hover:text-gray-900">Show Border</span>
						<p class="text-xs text-gray-400">Decorative border around the worksheet</p>
					</div>
				</label>
			</div>

			<!-- Error display -->
			{#if downloadError}
				<div class="bg-red-50 border border-red-200 rounded-lg p-3">
					<p class="text-sm text-red-700">{downloadError}</p>
				</div>
			{/if}

			<!-- Download buttons -->
			<div class="space-y-3">
				<Button
					class="w-full"
					size="lg"
					loading={isDownloading}
					onclick={handleDownloadPDF}
				>
					<svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
						<path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
					</svg>
					{isDownloading ? 'Preparing PDF...' : 'Download PDF'}
				</Button>

				<div class="grid grid-cols-2 gap-3">
					<Button variant="outline" onclick={handlePrint}>
						<svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
							<path stroke-linecap="round" stroke-linejoin="round" d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0021 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 00-1.913-.247M6.34 18H5.25A2.25 2.25 0 013 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.041 48.041 0 011.913-.247m10.5 0a48.536 48.536 0 00-10.5 0m10.5 0V3.375c0-.621-.504-1.125-1.125-1.125h-8.25c-.621 0-1.125.504-1.125 1.125v3.659M18 10.5h.008v.008H18V10.5zm-3 0h.008v.008H15V10.5z" />
						</svg>
						Print
					</Button>

					<Button variant="outline" onclick={handleSaveTemplate}>
						<svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
							<path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z" />
						</svg>
						Save Template
					</Button>
				</div>
			</div>

			<!-- Create another -->
			<div class="pt-4 border-t border-gray-200">
				<button
					class="w-full flex items-center justify-center gap-2 py-2.5 text-sm font-medium text-gray-500 hover:text-primary transition-colors"
					onclick={handleCreateAnother}
				>
					<svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
						<path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
					</svg>
					Create Another Worksheet
				</button>
			</div>
		</div>
	</div>
</div>
